### ISSUE TITLE
Repo oddskool/paiss_deeprl does not exist

### ISSUE THREAD

**Issue by MrLeylo** [criteo-research/paiss_deeprl#2]
I cannot neither clone it nor find it with my internet browser at the provided [link](https://github.com/oddskool/paiss_deeprl) .

**Comment by kir-dan** [comment]
I guess there is new link: https://github.com/criteo-research/paiss_deeprl.git

**Comment by MrLeylo** [comment]
I thought it was an additional repo. Thanks!

**Comment by oddskool** [comment]
thx, yes the repo url was fixed.
